### PR TITLE
Fix PHPMailer updates

### PR DESCRIPTION
**Pull request by xxsimoxx**

### CODE REVIEW

**Comment by azurecurve** [comment]
Why is a check for 1.5.0-rc1 required?

**Comment by xxsimoxx** [comment]
The new mailer will be reintroduced in 1.5.0 as I can see in the PR milestone.

**Comment by mattyrob** [comment]
Further changes may be made to the 1.4.x branch. Hold off this change yet and let’s work together to coordinate core and plugin changes to ensure compatibility.

**Comment by nylen** [comment]
Next time let's get in touch sooner if a release breaks something in a plugin people are using, I think it is worth working together to avoid that.

Something like this change has been released at https://forums.classicpress.net/t/smtp-v1-4-3-released/3944 but I don't see a corresponding commit to github.

The code that is in v1.4.3 of the plugin is

```php
if ( function_exists( 'classicpress_version' ) && version_compare( classicpress_version(), '1.4.0', 'ge' ) ) {
  // require new classes
} else {
  // require old class
}
```

Let's take a look at how it will behave.

- On CP 1.3.1 or earlier, this loads PHPMailer using the previous method and works fine.
- On CP 1.4.0, this detects the new location of the PHPMailer classes and requires them correctly.
- On CP 1.4.1 that has been upgraded from 1.4.0, the new PHPMailer classes are still present (they are not deleted on upgrade) and so they are required correctly.
- On CP 1.4.1 that is a fresh installation, the new PHPMailer classes are not present, so this code will fail.
- On CP 1.4.1 that has been upgraded from 1.3.1 or earlier, I believe this will also fail, but I haven't tested.
- On future versions of CP this should work fine.

You can see there are some issues but only with CP 1.4.1 and only in some situations. There are a couple of ways to fix this:

- You can always load the old classes, unless the specific CP version is 1.4.0. This would just change `'ge'` to `'e'` in the code that is currently shipped as plugin v1.4.3. We will be restoring compatibility for loading PHPMailer by requiring the old `class-phpmailer.php` in the next version of CP since this change broke a respectable number of sites.
- You can load the new classes in 1.4.0 and newer, but fall back to the old method for older versions and for version 1.4.1 specifically. We plan to retry this upgrade in the next version so the new classes will be available again.

The "next version of CP" referenced above may be 1.4.2 (my guess and my preference) or 1.5.0

Please let me know what you think.

**Comment by mattyrob** [comment]
@azurecurve - Please have a look at the update PR for ClassicPress - this may be further changed but I would welcome any feedback on this before we make the final change to see if we can do more to help ensure compatibility with your plugin.

**Comment by xxsimoxx** [comment]
I've done testing as you can see in https://github.com/ClassicPress/ClassicPress/pull/922 comments.

**Comment by mattyrob** [comment]
I wonder if an approach using file_exists() might offer wider compatibility.

**Comment by xxsimoxx** [comment]
> I wonder if an approach using file_exists() might offer wider compatibility.

~I've used `classicpress_version` because results of `file_exists` are cached and don't know if this can create troubles on upgrades. But if we are sure this is not a problem `file_exists` is cleaner.~ 

Done some test and `file_exists()` have no cache issues, so as mattyrob said it might offer wider compatibility and so **this is no more dependent from the CP version introducing/reverting/reintroducing the new PHPMailer**.

**Pull request merged**
